#ifndef OPCODES_HPP
#define OPCODES_HPP

#include <array>
#include <cstdint>
#include <string_view>

enum class AddressingMode
{
    IMMEDIATE,
    ZERO_PAGE,
    ZERO_PAGE_X,
    ZERO_PAGE_Y,
    ABSOLUTE,
    ABSOLUTE_X,
    ABSOLUTE_Y,
    INDIRECT_X,
    INDIRECT_Y,
    NONE
};

struct OpCode
{
    std::string_view name;
    std::uint8_t len;
    std::uint8_t cycles;
    AddressingMode mode;
};

constexpr std::array<OpCode, 0x100> OPCODES = {{
    /* 0x00 */ {"BRK", 1, 7, AddressingMode::NONE},
    /* 0x01 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x02 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x03 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x04 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x05 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x06 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x07 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x08 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x09 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x0A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x0B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x0C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x0D */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x0E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x0F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x10 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x11 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x12 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x13 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x14 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x15 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x16 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x17 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x18 */ {"CLC", 1, 2, AddressingMode::NONE},
    /* 0x19 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x1A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x1B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x1C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x1D */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x1E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x1F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x20 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x21 */ {"AND", 2, 6, AddressingMode::INDIRECT_X},
    /* 0x22 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x23 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x24 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x25 */ {"AND", 2, 3, AddressingMode::ZERO_PAGE},
    /* 0x26 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x27 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x28 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x29 */ {"AND", 2, 2, AddressingMode::IMMEDIATE},
    /* 0x2A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x2B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x2C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x2D */ {"AND", 3, 4, AddressingMode::ABSOLUTE},
    /* 0x2E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x2F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x30 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x31 */ {"AND", 2, 5 /*+1 if page crossed*/, AddressingMode::INDIRECT_Y},
    /* 0x32 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x33 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x34 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x35 */ {"AND", 2, 4, AddressingMode::ZERO_PAGE_X},
    /* 0x36 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x37 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x38 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x39 */ {"AND", 3, 4 /*+1 if page crossed*/, AddressingMode::ABSOLUTE_Y},
    /* 0x3A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x3B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x3C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x3D */ {"AND", 3, 4 /*+1 if page crossed*/, AddressingMode::ABSOLUTE_X},
    /* 0x3E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x3F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x40 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x41 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x42 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x43 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x44 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x45 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x46 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x47 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x48 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x49 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x4A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x4B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x4C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x4D */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x4E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x4F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x50 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x51 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x52 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x53 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x54 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x55 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x56 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x57 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x58 */ {"CLI", 1, 2, AddressingMode::NONE},
    /* 0x59 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x5A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x5B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x5C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x5D */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x5E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x5F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x60 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x61 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x62 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x63 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x64 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x65 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x66 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x67 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x68 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x69 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x6A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x6B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x6C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x6D */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x6E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x6F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x70 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x71 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x72 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x73 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x74 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x75 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x76 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x77 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x78 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x79 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x7A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x7B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x7C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x7D */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x7E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x7F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x80 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x81 */ {"STA", 2, 6, AddressingMode::INDIRECT_X},
    /* 0x82 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x83 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x84 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x85 */ {"STA", 2, 3, AddressingMode::ZERO_PAGE},
    /* 0x86 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x87 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x88 */ {"DEY", 1, 2, AddressingMode::NONE},
    /* 0x89 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x8A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x8B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x8C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x8D */ {"STA", 3, 4, AddressingMode::ABSOLUTE},
    /* 0x8E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x8F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x90 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x91 */ {"STA", 2, 6, AddressingMode::INDIRECT_Y},
    /* 0x92 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x93 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x94 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x95 */ {"STA", 2, 4, AddressingMode::ZERO_PAGE_X},
    /* 0x96 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x97 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x98 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x99 */ {"STA", 3, 5, AddressingMode::ABSOLUTE_Y},
    /* 0x9A */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x9B */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x9C */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x9D */ {"STA", 3, 5, AddressingMode::ABSOLUTE_X},
    /* 0x9E */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0x9F */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA0 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA1 */ {"LDA", 2, 6, AddressingMode::INDIRECT_X},
    /* 0xA2 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA3 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA4 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA5 */ {"LDA", 2, 3, AddressingMode::ZERO_PAGE},
    /* 0xA6 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA7 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA8 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xA9 */ {"LDA", 2, 2, AddressingMode::IMMEDIATE},
    /* 0xAA */ {"TAX", 1, 2, AddressingMode::NONE},
    /* 0xAB */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xAC */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xAD */ {"LDA", 3, 4, AddressingMode::ABSOLUTE},
    /* 0xAE */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xAF */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB0 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB1 */ {"LDA", 2, 5 /*+1 if page crossed*/, AddressingMode::INDIRECT_Y},
    /* 0xB2 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB3 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB4 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB5 */ {"LDA", 2, 4, AddressingMode::ZERO_PAGE_X},
    /* 0xB6 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB7 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xB8 */ {"CLV", 1, 2, AddressingMode::NONE},
    /* 0xB9 */ {"LDA", 3, 4 /*+1 if page crossed*/, AddressingMode::ABSOLUTE_Y},
    /* 0xBA */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xBB */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xBC */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xBD */ {"LDA", 3, 4 /*+1 if page crossed*/, AddressingMode::ABSOLUTE_X},
    /* 0xBE */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xBF */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xC0 */ {"CPY", 2, 2, AddressingMode::IMMEDIATE},
    /* 0xC1 */ {"CMP", 2, 6, AddressingMode::INDIRECT_X},
    /* 0xC2 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xC3 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xC4 */ {"CPY", 2, 3, AddressingMode::ZERO_PAGE},
    /* 0xC5 */ {"CMP", 2, 3, AddressingMode::ZERO_PAGE},
    /* 0xC6 */ {"DEC", 2, 5, AddressingMode::ZERO_PAGE},
    /* 0xC7 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xC8 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xC9 */ {"CMP", 2, 2, AddressingMode::IMMEDIATE},
    /* 0xCA */ {"DEX", 1, 2, AddressingMode::NONE},
    /* 0xCB */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xCC */ {"CPY", 3, 4, AddressingMode::ABSOLUTE},
    /* 0xCD */ {"CMP", 3, 4, AddressingMode::ABSOLUTE},
    /* 0xCE */ {"DEC", 3, 6, AddressingMode::ABSOLUTE},
    /* 0xCF */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xD0 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xD1 */ {"CMP", 2, 5 /*+1 if page crossed*/, AddressingMode::INDIRECT_Y},
    /* 0xD2 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xD3 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xD4 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xD5 */ {"CMP", 2, 4, AddressingMode::ZERO_PAGE_X},
    /* 0xD6 */ {"DEC", 2, 6, AddressingMode::ZERO_PAGE_X},
    /* 0xD7 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xD8 */ {"CLD", 1, 2, AddressingMode::NONE},
    /* 0xD9 */ {"CMP", 3, 4 /*+1 if page crossed*/, AddressingMode::ABSOLUTE_Y},
    /* 0xDA */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xDB */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xDC */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xDD */ {"CMP", 3, 4 /*+1 if page crossed*/, AddressingMode::ABSOLUTE_X},
    /* 0xDE */ {"DEC", 3, 7, AddressingMode::ABSOLUTE_X},
    /* 0xDF */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE0 */ {"CPX", 2, 2, AddressingMode::IMMEDIATE},
    /* 0xE1 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE2 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE3 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE4 */ {"CPX", 2, 3, AddressingMode::ZERO_PAGE},
    /* 0xE5 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE6 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE7 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xE8 */ {"INX", 1, 2, AddressingMode::NONE},
    /* 0xE9 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xEA */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xEB */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xEC */ {"CPX", 3, 4, AddressingMode::ABSOLUTE},
    /* 0xED */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xEE */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xEF */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF0 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF1 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF2 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF3 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF4 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF5 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF6 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF7 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF8 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xF9 */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xFA */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xFB */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xFC */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xFD */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xFE */ {"   ", 0, 0, AddressingMode::NONE},
    /* 0xFF */ {"   ", 0, 0, AddressingMode::NONE},
}};

#endif /* OPCODES_HPP */
